Ikbal caprover
jabardigitalservice/pikobar-logistik-frontend pull request #263
Opened 2021-04-22 03:47 UTC by mhdikbal

Bang Rindi, i need your advice.
Sebagaimana diskusi sebelumnya perihal menjalankan code pikobar-logistik-frontend di caprover, aku mengajukan PR untuk merge branch ikbal-caprover ke branch development. Adapun perubahan yang aku lakukan sebagai berikut ini;

1. Membikin file captain-defenition 
2. Membikin file Dockerfile-caprover

2021-04-22 04:09 UTC, rindibudiaramdhan approved these changes
untuk mengatasi beberapa issue, maka dilakukan:
- penambahan baris `RUN rm -rf package-lock.json` di Dockerfile.caprover karena issue package
- jika di run di local ada issue harus memasang `https`. dan uji coba di development caprover berjalan dengan baik.

2021-04-22 04:41 UTC, smilelikeshit approved these changes

2021-04-23 06:18 UTC, yohang88 requested changes
Ini saya sudah bilang ya, seharusnya Dockerfile ga dipisahkan khusus untuk caprover.

2021-04-23 06:29 UTC, rindibudiaramdhan commented
> Ini saya sudah bilang ya, seharusnya Dockerfile ga dipisahkan khusus untuk caprover.

ya, baik mas @yohang88 
Hari ini sudah didiskusikan issuenya terkait caprover logistik-fe. Hasilnya 
- `package-lock.json` di FE ada issue dan akan diperbaiki secepatnya. Kesimpulan ini setelah uji coba di repo yang lain yang memiliki `package-lock.json` dan berhasil.
- `Dockerfile.caprover` akan dihilangkan dan tetap menggunakan `Dockerfile` yang sudah ada untuk consume deploy di caprovernya.

2021-04-23 08:24 UTC, mhdikbal commented
Hasil setelah concall, berikut saya sampaikan perbaikan daripada issue package-lock.json.

1. Pastikan node yang digunakan sama dengan docker node version pada Dockerfile
2. generate ulang package-lock.json
`npm install --package-lock`

2021-04-23 08:26 UTC, yohang88 approved these changes
Oke sip @mhdikbal 👍

2021-04-23 08:27 UTC, merged